# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=15)),
                ('group_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=60)),
                ('display_name', models.CharField(max_length=60)),
                ('business_type', models.CharField(max_length=3)),
                ('owner1_name', models.CharField(max_length=30)),
                ('owner1_pan', models.CharField(max_length=10)),
                ('is_id_proof1', models.BooleanField()),
                ('owner1_mobile', models.IntegerField()),
                ('owner1_landline', models.IntegerField()),
                ('owner2_name', models.CharField(max_length=30)),
                ('owner2_pan', models.CharField(max_length=10)),
                ('is_id_proof2', models.BooleanField()),
                ('owner2_mobile', models.IntegerField()),
                ('owner2_landline', models.IntegerField()),
                ('business_pincode', models.IntegerField()),
                ('business_address', models.CharField(max_length=50)),
                ('business_address2', models.CharField(max_length=50)),
                ('business_city', models.CharField(max_length=30)),
                ('business_state', models.CharField(max_length=2)),
                ('business_phone', models.IntegerField()),
                ('business_email', models.EmailField(max_length=256)),
                ('business_website_domain', models.EmailField(max_length=256)),
                ('business_website_redirect', models.CharField(max_length=1024)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AxisChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epay', models.BooleanField()),
                ('ibank', models.BooleanField()),
                ('mpos', models.BooleanField()),
                ('lead_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='merchants.Axis')),
            ],
        ),
        migrations.CreateModel(
            name='AxisEpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField()),
                ('live_date', models.DateTimeField()),
                ('initial_tcount', models.IntegerField()),
                ('expected_tcount', models.IntegerField()),
                ('lead_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='merchants.Axis')),
            ],
        ),
        migrations.CreateModel(
            name='AxisIBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=10)),
                ('card', models.CharField(max_length=20)),
                ('sec_enabled', models.BooleanField()),
                ('disp_format', models.IntegerField()),
                ('web_access', models.BooleanField()),
                ('provider', models.IntegerField()),
                ('lead_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='merchants.Axis')),
            ],
        ),
        migrations.CreateModel(
            name='Financials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField()),
                ('current', models.BooleanField()),
                ('account_no', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=50)),
                ('lead_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='merchants.Axis')),
            ],
        ),
    ]
